[supabase]
host = "aws-1-ap-south-1.pooler.supabase.com"
database = "postgres"
user = "postgres.qxgxodpethnqmwheyepq"
password = "Vaishnani@2728"
port = 6543

[gemini]
api_key = "AIzaSyD6oYk5hTaf_Ki4AOp-BN8o7e-PtuSg-wg"